
    # Utilize a versão “3” no arquivo;
    # Crie um service para subir a plataforma, utilize a imagem ghost:1-alpine;
    # Publique a porta 2368, fazendo bind também para a 2368;
    # Suba a aplicação utilizando o docker-compose e então acesse a porta publicada para validar se deu tudo certo.


version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368